# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0d1710d0-0752-4d30-bbc0-a9817efca021";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-c56d30ef-9310-49cd-a483-229d28675e21".device = "/dev/disk/by-uuid/c56d30ef-9310-49cd-a483-229d28675e21";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/413B-095C";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  # NOTE: disabled because the gui installer didn't seem to create this partition and it's
  # causing a start job to fail that causes slow boot
  # swapDevices =
  #   [ { device = "/dev/disk/by-uuid/6cdaf02a-da3e-4fd0-90f5-f155b5e76a20"; }
  #   ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
