-- which-key helps you remember key bindings by showing a popup
-- with the active keybindings of the command you started typing.
return {
   'folke/which-key.nvim',
   event = 'VeryLazy',
   opts = {
      plugins = { spelling = true },
      spec = {
         mode = { 'n', 'v' },
         { 'g', group = '+goto' },
         { 'gs', group = '+surround' },
         { 'x', group = '+comment' },
         { ']', group = '+next' },
         { '[', group = '+prev' },
         { '<leader>b', group = '+buffer' },
         { '<leader>c', group = '+code' },
         { '<leader>cp', group = '+copilot' },
         { '<leader>cpC', group = '+copilot chat' },
         { '<leader>d', group = '+debug' },
         { '<leader>D', group = '+diagnostics/quickfix' },
         { '<leader>E', group = '+editor' },
         { '<leader>f', group = '+find/file' },
         { '<leader>g', group = '+git' },
         { '<leader>gh', group = '+hunks' },
         { '<leader>h', group = '+harpoon' },
         { '<leader>m', group = '+misc' },
         { '<leader>md', group = '+duck' },
         { '<leader>mf', group = '+fuck' },
         { '<leader>mfm', group = '+my' },
         { '<leader>mh', group = '+hack' },
         { '<leader>o', group = '+options'},
         { '<leader>p', group = '+plugins' },
         { '<leader>q', group = '+quit/session' },
         { '<leader>s', group = '+search' },
         { '<leader>sn', group = '+neovim' },
         { '<leader>sN', group = '+noice' },
         { '<leader>u', group = '+ui' },
         { '<leader>w', group = '+windows' },
      },
      icons = {
         -- set icon mappings to true if you have a Nerd Font
         mappings = vim.g.have_nerd_font,
         -- If you are using a Nerd Font: set icons.keys to an empty table which will use the
         -- default which-key.nvim defined Nerd Font icons, otherwise define a string table
         keys = vim.g.have_nerd_font and {} or {
            Up = '<Up> ',
            Down = '<Down> ',
            Left = '<Left> ',
            Right = '<Right> ',
            C = '<C-…> ',
            M = '<M-…> ',
            D = '<D-…> ',
            S = '<S-…> ',
            CR = '<CR> ',
            Esc = '<Esc> ',
            ScrollWheelDown = '<ScrollWheelDown> ',
            ScrollWheelUp = '<ScrollWheelUp> ',
            NL = '<NL> ',
            BS = '<BS> ',
            Space = '<Space> ',
            Tab = '<Tab> ',
            F1 = '<F1>',
            F2 = '<F2>',
            F3 = '<F3>',
            F4 = '<F4>',
            F5 = '<F5>',
            F6 = '<F6>',
            F7 = '<F7>',
            F8 = '<F8>',
            F9 = '<F9>',
            F10 = '<F10>',
            F11 = '<F11>',
            F12 = '<F12>',
         },
      },
   },
}
