#!/usr/bin/env bash

#!/usr/bin/env bash

nix flake update --flake ~/source/nixCats

nixcats --headless "+Lazy! update" +qa

nix build ~/source/nixCats

# Navigate to the nixCats directory and perform git operations
cd ~/source/nixCats
git add .
git commit -m "nvim auto update [$(date +'%Y-%m-%d %H:%M:%S')]"
git push
cd -

nix flake update --flake ~/.nix mynvim

home-manager switch -b backup --flake ~/.nix
