#!/usr/bin/env bash

ORIGINAL_DIR=$(pwd)
trap 'cd "$ORIGINAL_DIR"' EXIT

# Navigate to the nixCats directory to perform git operations
cd ~/source/nixCats
git pull --rebase

nix flake update --flake ~/source/nixCats

nixcats --headless "+Lazy! update" +qa

nix build ~/source/nixCats

git add .
git commit -m "nvim auto update [$(date +'%Y-%m-%d %H:%M:%S')]"
git push

# Navigate to the nix directory to perform git operations
cd ~/.nix
git pull --rebase
nix flake update --flake ~/.nix mynvim
git add .
git commit -m "Nvim flake update [$(date +'%Y-%m-%d %H:%M:%S')]"
git push

home-manager switch -b backup --flake ~/.nix
